apiVersion: v1
kind: Service
metadata:
  name: qna-agent
  labels:
    app: qna-agent
spec:
  type: ClusterIP
  selector:
    app: qna-agent
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
